### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by dionhaefner** [DHI-GRAS/hillshade#1]
I know you're not quite done with the code yet, but I wanted to give you a first code review to give you an idea about what's left to do. I am purely reviewing the structure and style of the code, not the functionality.

## General

- First up: well done! You did a good job picking up the right idioms when working with `click`, `numba`, and `rasterio`.
- Make sure that your code is `flake8` compatible, and set up a job on Travis to check that after every commit. There are tons of PEP8 violations in your code, but your linter will catch that, so I won't correct them explicitly in the following review.
- Type annotations only make sense if you check them. For static type analysis we use [mypy](http://mypy-lang.org/). See [Terracotta](https://github.com/DHI-GRAS/terracotta)'s `setup.cfg` and `travis.yml` for inspiration. Type checking should be part of the CI job.
- On docstrings: When using type annotations, I often find documenting all input parameters a bit redundant, if the names are expressive enough by itself. However, I *do* think that every function deserves at least a one-line docstring outlining its purpose.

## `cli.py`

- When importing so many packages, we like to separate standard library and third-party imports with an empty line.
- We try to avoid the older `from .x import y` syntax. Go for absolute imports instead: `from hillshade.hillshade import hillshade`.
- We use single quotes `'` for strings instead of double quotes `"` (you'll get used to it).
- `_get_metafile`: fail gracefully if glob pattern is empty
- `_get_node`: missing type annotation
- `_get_mean_angles`: Typo (`Unkown`)
- We use Python 3 format strings instead of `.format` in most cases: `raise ValueError(f'Unkown angle: {angle.tag}')`
- You are not checking whether both `zenith` and `azimuth` were found.
- In fact, all your parsing functions could be written a lot more concisely by using XML's [XPath](https://docs.python.org/2/library/xml.etree.elementtree.html#xpath-support) capability.
- `_get_resolution`: I don't know if you are deliberately grabbing the last matching row in the meta file - if not, you could return early and eliminate most of the logic here.
- `xyray_vector`: Please use more descriptive names, and / or a docstring. I don't understand what this function does.
- `_run_shader`: We usually iterate directly over `tqdm` progress bars:

   ```python
   progress = tqdm.tqdm(iterable)
   for item in progress:
      ...
   ```

   That way, you save yourself the setup, teardown, and update of the progress bar. If this is not an option, use it as a context manager (`with tqdm.tqdm(...) as pbar`) instead of calling `pbar.close()` manually.
- `cli`: Line continuation characters are not needed in docstrings. However, for multi-line strings we prefer simple concatenation:

   ```python
   @click.option(
        help='Chunk size of the image in y direction that is processed at a time. '
             'Only affects the progress bar update frequency. Defaults to 100.')
   ```
- Instead of stating the default in the `help` string, you can set `show_default=True`.
- Instead of `click.Path(file_okay=True)` you want `click.Path(dir_okay=False)`.
- Use `click.Integer()` instead of `int`.
- In our experience, CLIs with more that one positional argument (where the ordering is non-obvious) are often not intuitive. Your infile and outfile arguments should really be (required) options.
- Do `src.read(1)` instead of `src.read()[0]`. This saves you from reading all bands in a multi-band file.
- Are you sure you want `nodata=None`? What if your input file contains missing values?

## `hillshade.py`

- Please use more descriptive parameter names. `model`, `ray`, `shadow` are not really expressive enough for me understand at a glance what you're doing. What's the difference between `x0` and `x`?
- You don't have to specify the signature for your helper functions - the types will be inferred during compilation of the main function (`hillshade`).

**Comment by nmheim** [comment]
Done!
