### ISSUE TITLE
Make the globber less globby

### ISSUE THREAD

**Issue by milyra** [DHI-GRAS/hillshade#2]
Currently, the globber that finds folders is very inclusive. A nice little improvement would be to actually only assess folders that match the Sentinel-2 naming convention, so that the script doesn't try to consume errant `.bat-files` and similar.

**Comment by j08lue** [comment]
Couldn't you use a pattern like `*.SAFE` for that?

**Comment by milyra** [comment]
That is true - I will edit the usage-example to reflect that approach.
